### ISSUE TITLE
Move from ExcelReaders to XLSX

### ISSUE THREAD

**Issue by lrennels** [AlexandrePavlov/MimiDICE2016.jl#12]
HI @AlexandrePavlov, per an issue brought up on the forum about DICE2010 here: 

https://forum.mimiframework.org/t/mimidice2010-get-model-pyerror-excel-xlsx-file-not-supported/145/5

and some digging results ing this information: 

https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported

**updateI** @AlexandrePavlov I actually think the best solution is actually to move from ExcelReaders.jl to XLSX.jl which we had open PRs on for DICE2013 and DICE2010 but never merged.  Let me do that and if it works I'll let you know and you can just copy those PRs.

**Comment by AlexandrePavlov** [comment]
Got it! I'll wait to see if that fixes the problem for DICE2010 and do the same for DICE2016.

**Comment by lrennels** [comment]
@AlexandrePavlov we could probably also shift to  a different package, there was an outstanding PR on DICE2010 about it, I"ll ask @davidanthoff  

https://github.com/anthofflab/MimiDICE2010.jl/pull/18
